### ISSUE TITLE
Missing or function.

### ISSUE THREAD

**Issue by JoakimCh** [consento-org/longfn#1]
To my supprise there is no `or` function implemented, I guess this was a mistake?

Maybe this will do:
```js
function or (long, other, target) {
  target.low = long.low | other.low
  target.high = long.high | other.high
  target.unsigned = !!long.unsigned
  return target
}
```

**Comment by martinheidegger** [comment]
Thank you @JoakimCh for pointing that out, I think I missed it when I first ported it! Good catch! I opened PR #3 to fix this issue.
