### ISSUE TITLE
[bug] fromInt(0xFFFF_FFFF, true) gives 0x1_0000_0000_0000_0000

### ISSUE THREAD

**Issue by JoakimCh** [consento-org/longfn#2]
`fromInt(0xFFFF_FFFF, true)` gives `0x1_0000_0000_0000_0000`
I don't see how this is correct.

**Comment by martinheidegger** [comment]
Can you elaborate how you are getting `0x1_0000_0000_0000_0000`? in my tests `fromInt(0xFFFF_FFFF, true)` gives `0xFFFF_FFFF_FFFF_FFFF`, the same as`fromInt(-1, true)` as the `0xFFFF_FFFF` overflows the integer limit and is assumed as -1. If you wish to get the equivalent of `0xFFFF_FFFF` as long number maybe you want to use the `fromNumber(0xFFFF_FFFF, true)` operation?

```javascript
const { fromInt, toString } = require('longfn')
console.log(`0x${toString(fromInt(0xFFFF_FFFF, true), 16).toUpperCase()})
```

This is the same behavior as in [long.js](https://github.com/dcodeIO/long.js#readme). Maybe better documentation is necessary?

**Comment by JoakimCh** [comment]
Sorry, I was confused. I somehow thought that `fromInt` was an alias for `fromInt32`.
Hence I did something like this:
`console.log(longfn.toNumber(longfn.fromInt(0xFFFF_FFFF, true)).toString(16))`
